/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        error: '#ba1a1a',
        'on-secondary': '#ffffff',
        'secondary-container': '#316bf3',
        'primary-fixed': '#dae2fd',
        'surface-container-low': '#eff4ff',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#003ea8',
        surface: '#f8f9ff',
        'on-primary-fixed-variant': '#3f465c',
        'on-primary': '#ffffff',
        'surface-container': '#e5eeff',
        'on-background': '#0b1c30',
        'on-tertiary-fixed-variant': '#005137',
        'outline-variant': '#c6c6cd',
        'on-tertiary-container': '#069669',
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#fefcff',
        'on-surface': '#0b1c30',
        'on-primary-fixed': '#131b2e',
        'on-tertiary-fixed': '#002114',
        'inverse-on-surface': '#eaf1ff',
        background: '#f8f9ff',
        'tertiary-fixed': '#85f8c4',
        'on-error': '#ffffff',
        'on-secondary-fixed': '#00174b',
        primary: '#000000',
        'surface-container-high': '#dce9ff',
        'primary-container': '#131b2e',
        'inverse-surface': '#213145',
        tertiary: '#000000',
        'inverse-primary': '#bec6e0',
        'tertiary-fixed-dim': '#68dba9',
        'surface-container-highest': '#d3e4fe',
        'surface-variant': '#d3e4fe',
        outline: '#76777d',
        'primary-fixed-dim': '#bec6e0',
        secondary: '#0051d5',
        'surface-tint': '#565e74',
        'error-container': '#ffdad6',
        'tertiary-container': '#002114',
        'on-error-container': '#93000a',
        'secondary-fixed': '#dbe1ff',
        'surface-bright': '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'secondary-fixed-dim': '#b4c5ff',
        'on-surface-variant': '#45464d',
        'on-primary-container': '#7c839b',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        gutter: '1.5rem',
        margin: '2rem',
        'space-xl': '2rem',
        'space-lg': '1.5rem',
        'margin-mobile': '1rem',
        'gutter-mobile': '1rem',
        'space-md': '1rem',
        'space-sm': '0.5rem',
      },
      fontFamily: {
        'headline-lg': ['Inter'],
        'body-lg': ['Inter'],
        'headline-xl-mobile': ['Inter'],
        'headline-sm': ['Inter'],
        'body-sm': ['Inter'],
        'headline-xl': ['Inter'],
        'label-badge': ['Inter'],
        'label-subtext': ['Inter'],
        'body-md': ['Inter'],
        'label-code': ['JetBrains Mono'],
        sans: ['Inter', 'ui-sans-serif', 'system-ui'],
      },
      fontSize: {
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'headline-xl-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.025em', fontWeight: '600' }],
        'label-badge': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-subtext': ['11px', { lineHeight: '14px', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'label-code': ['12px', { lineHeight: '16px', letterSpacing: '-0.01em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
